import pygame

pygame.init()

width = 500
height = 500
clock = pygame.time.Clock()

Click = 0
set =(0,0,0)
screen = pygame.display.set_mode((width,height))

pygame.display.set_caption("MENU")

def draw_text(text,font,text_col,x,y):
    img = font.render(text,True,text_col)
    screen.blit(img,(x,y))

def click(Click):
    if pygame.mouse.get_pressed == True:
        screen.fill(set)
        Click += 1
    return Click
#loop
run = True
while run:
    if Click < 10:
        screen.fill((52,78,91))
    else:
        screen.fill(set)

    #event handler

    for event in pygame.event.get():
        if event.type == pygame.QUIT:
            run = False

    click(Click)

    clock.tick(60)
    pygame.display.update()

pygame.quit()

